Properly hiddes assets from dashboard when they are in the ignore list
rotki/rotki pull request #1529
Opened 2020-10-02 14:08 UTC by kelsos

Closes #1501

2020-10-03 20:30 UTC, LefterisJP reviewed
I tested it and it works. But it just works for the dashboard.

Shouldn't this be also extended to:

Blockchain balances and exchange balances and manual balances? (okay last one may not make sense -- but the rest do imo)

2020-10-03 20:30 UTC, LefterisJP commented on frontend/app/src/locales/en.json
> +      "tax_free_days_gt_zero": "The number of days cannot negative or zero"
cannot negative -> cannot be negative

2020-10-05 08:41 UTC, LefterisJP requested changes
@kelsos There is a serious problem introduced by this PR. I can no longer expand ethereum accounts and see what assets each one owns

2020-10-05 08:42 UTC, kelsos commented
OK let me check it the fix should be simple

2020-10-05 11:00 UTC, LefterisJP approved these changes
LGTM now

2020-10-05 11:30 UTC, kelsos commented
@LefterisJP backend tests failed on travis, I am merging

2020-10-05 11:30 UTC, merged

2020-10-05 11:34 UTC, LefterisJP commented
Hmm please don't merge without explaining why you chose to ignore the failing of the backend tests. For example you must have seen I always check if it's a problem with one of the remotes the test may have failed to contact e.t.c.

I made an issue for the failure: https://github.com/rotki/rotki/issues/1550

2020-10-05 13:10 UTC, kelsos commented
@LefterisJP Well the reasoning is simple, this PR is only changing the frontend of the application. Regarding the mergability of the PR, it doesn't really matter which backend test failed and why. Does it? There was no modification of the python code, which means that whatever the problem, was not introduced by this PR. 

Furthermore, I just pinged you since it didn't seem like a remote service issue :) In the future, I will try adding more information in regards to the type of failure.