feat: refactor api
rotki/rotki pull request #5259
Opened 2022-12-14 08:46 UTC by lukicenturi

Part of #4872

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

2022-12-15 21:06 UTC, kelsos requested changes
Thanks for taking this over.

My comments are mostly 

- about treating apis as composables, and destructuring them when using them.
- about converting `promise.then` to `async` `await` in the apis we touch in this pr
- about converting `function` to `const x => {}` in the apis we touch in this PR,

finally I also have a question to a change that doesn't seem related to the PR

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/defi/sushiswap/index.ts
> +  const api = useSushiswapApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/defi/yearn/index.ts
> +  const api = useYearnApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/defi/index.ts
> +  const api = useDefiApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/defi/uniswap.ts
> +  const api = useUniswapApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/history/asset-movements.ts
> +  const api = useAssetMovementsApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/history/ledger-actions.ts
> +  const api = useLedgerActionsApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/history/trades.ts
> +  const api = useTradesApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/history/transactions.ts
> +  const api = useTransactionsApi();
destructure

2022-12-15 21:06 UTC, kelsos commented on frontend/app/src/store/reports/index.ts
> +  const historyApi = useHistoryApi();
destructure

2022-12-16 07:06 UTC, lukicenturi commented on frontend/app/src/components/settings/data-security/DataManagement.vue
> +  const { deleteExchangeData } = useExchangeApi();
sorry I don't get it, which setup context?

2022-12-16 07:46 UTC, lukicenturi commented on frontend/app/src/store/blockchain/index.ts
> +          );
I change it to `startPromise` instead, so this function is done in the line before `await fetchAccounts(blockchain);`
So the bottom drawer can be closed immediately. (dont need to wait for the balances to be fetched first)

2022-12-16 07:47 UTC, lukicenturi commented on frontend/app/src/store/blockchain/index.ts
> +        startPromise(fetchNonFungibleBalances(true));
same like above, but for this make sure they are executed in order. (Is there any better way to write this)

2022-12-19 11:13 UTC, kelsos commented on frontend/app/src/store/blockchain/index.ts
> +          );
I will merge as it is and think of a way. But if something needs to run sequentially we have to await, `startPromise` is for when we don't care about sequence, it is kind of fire and forget.

2022-12-19 11:14 UTC, kelsos approved these changes
I will do some small check changes on the blockchain account addition my self but the reset looks good.

2022-12-19 11:15 UTC, merged