feat: add e2e test for trade filter and pagination
rotki/rotki pull request #5674
Opened 2023-02-27 08:30 UTC by lukicenturi

Closes #5652

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

2023-02-27 09:06 UTC, kelsos commented on frontend/app/package.json
> -    "electron": "22.3.0",
can you rollback this to 22.x ? 

https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-in-early-2023?hl=en

2023-02-27 14:42 UTC, kelsos requested changes

2023-02-27 14:42 UTC, kelsos commented on frontend/app/src/store/defi/protocols/index.ts
> +                sum.plus(collateral.collateral.usdValue),
can we at least do some destructuring to avoid collateral.collateral?

2023-02-27 14:42 UTC, kelsos commented on frontend/app/src/store/defi/protocols/index.ts
> +            .reduce((sum, debt) => sum.plus(debt.debt.usdValue), Zero)
same here to avoid debt.debt

2023-02-27 14:42 UTC, kelsos commented on frontend/app/src/store/defi/protocols/index.ts
> +            (sum, value) => sum.plus(value.underlyingValue.usdValue),
same here do some basic destructuring

2023-02-27 14:42 UTC, kelsos commented on frontend/app/tests/e2e/specs/2/history/trade-history.spec.ts
> +  // });
These 3 tests should not be commented.

2023-02-28 05:28 UTC, lukicenturi commented on frontend/app/tests/e2e/specs/2/history/trade-history.spec.ts
> +  // });
my bad

2023-02-28 09:50 UTC, kelsos approved these changes
lgtm

2023-02-28 11:51 UTC, merged