Add PulseChain as a ChainID
rotki/rotki pull request #7577
Opened 2024-03-04 18:01 UTC by coinyon

This adds support for PulseChain in the ChainID enum. I'm unsure if anything else is needed to allow users to add their own PulseChain tokens.

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

2024-03-06 13:41 UTC, lukicenturi approved these changes

2024-03-06 13:41 UTC, lukicenturi reviewed
Thanks for the PR.

You need to do 1 more thing, which is to add the icon on the frontend.
You can put `pulsechain.svg` in this directory `frontend/app/public/assets/images/protocols`

2024-03-06 13:42 UTC, lukicenturi requested changes
Thanks for the PR. @coinyon 

You need to do 1 more thing, which is to add the icon, in order to show it correctly in frontend.
You can put `pulsechain.svg` in this directory `frontend/app/public/assets/images/protocols`

2024-03-10 15:37 UTC, coinyon commented
Thanks, added the logo and rebased. Anything else?

2024-03-11 04:06 UTC, lukicenturi approved these changes

2024-03-11 04:06 UTC, merged